name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install NDK
      run: $ANDROID_HOME/tools/bin/sdkmanager "ndk;20.0.5594570" "cmake;3.10.2.4988404"
    - name: Build with Gradle
      run: ./gradlew build
